name: nijimas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  hooks_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  google_sign_in: ^6.2.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter_gen:
  integrations:
    flutter_svg: true
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/nijimas.png
    - assets/title.png
    - assets/google.png
