name: nijimas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  hooks_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  google_sign_in: ^6.2.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  logger: ^2.2.0
  go_router: ^13.2.2
  flutter_hooks: ^0.20.5
  loading_animation_widget: ^1.2.1
  cloud_firestore: ^4.15.8
  google_fonts: 6.1.0
  wave: ^0.2.2
  json_annotation: ^4.8.1
  top_snackbar_flutter: ^3.1.0
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  stylish_bottom_bar: ^1.1.0
  image_picker: ^1.1.0
  image: ^4.1.7
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  flutter_picker: ^2.1.0
  toggle_switch: ^2.3.0
  uuid: ^4.4.0
  firebase_storage: ^11.7.4
  bottom_picker: ^2.7.0
  freezed: ^2.5.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.2
  json_serializable: ^6.7.1
  test: ^1.25.2

flutter_gen:
  integrations:
    flutter_svg: true
flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/nijimas.png
    - assets/title.png
    - assets/google.png
    - assets/placeholder.png
